# Watch any file in the src directory - change as required
# Output directory set as output:
# Input directory set as input:
guard :entangle, input: 'src', output: 'js' do
    watch(%r{^src/.+\..+$})
end